# go to https://rplace.space/combined/
# and look for the id of your start and end image
timelapse:
  image-range:
    start: 1648948834
    end: 1649113741
  # if 1 - takes every image, if 3 - takes every third image
  frame_granularity: 1

place-canvas:
  top-left-coordinates:
    x: 1460
    y: 430
  dimensions:
    width: 150
    height: 150

output:
  name: "ethz-epfl"
  dimensions:
    width: 600
    height: 600
  

